# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from qtwidgets import PasswordEdit
from PyQt5.QtWidgets import QListWidget

class Ui_App(object):
    def setupUi(self,App):
        App.setObjectName("App")
        App.resize(1920, 1080)
        #Login client
        App.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        App.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(App)
        self.widget.setGeometry(QtCore.QRect(610, 70, 641, 741))
        self.widget.setStyleSheet("border-radius:50px;\n"
"background-color: rgb(77, 77, 77);\n"
"")
        self.widget.setObjectName("widget")
        self.TitleLogin = QtWidgets.QLabel(self.widget)
        self.TitleLogin.setGeometry(QtCore.QRect(260, 110, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLogin.setFont(font)
        self.TitleLogin.setStyleSheet("color:rgb(255,255,255)")
        self.TitleLogin.setObjectName("label")
        self.Email = QtWidgets.QLineEdit(self.widget)
        self.Email.setGeometry(QtCore.QRect(120, 250, 400, 50))
        self.Email.setAutoFillBackground(False)
        self.Email.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(211, 211, 211);\n"
"padding-left:7px;\n"
"color: rgb(40, 40, 40);\n"
"\n"
"")
        self.Email.setText("")
        self.Email.setObjectName("Email")
        
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(120, 360, 400, 50))
        self.password.setAutoFillBackground(False)
        self.password.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(211, 211, 211);\n"
"padding-left: 7px;\n"
"color: rgb(40, 40, 40)\n"
"\n"
"")
        self.password.setText("")
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.AppNametext = QtWidgets.QLabel(self.widget)
        self.AppNametext.setGeometry(QtCore.QRect(170, 0, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AppNametext.setFont(font)
        self.AppNametext.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: none;")
        self.AppNametext.setObjectName("AppNametext")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(120, 500, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.943, x2:1, y2:0, stop:0 rgba(84, 176, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.766, y1:0.153409, x2:1, y2:0, stop:0 rgba(84, 241, 236, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#pushButton:press{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(117, 255, 251)\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(150, 450, 101, 20))
        self.checkBox.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.wellcomebacktext = QtWidgets.QLabel(self.widget)
        self.wellcomebacktext.setGeometry(QtCore.QRect(240, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wellcomebacktext.setFont(font)
        self.wellcomebacktext.setStyleSheet("color: rgb(255, 255, 255);")
        self.wellcomebacktext.setObjectName("wellcomebacktext")
        self.Hidepassword = QtWidgets.QPushButton(self.widget)
        self.Hidepassword.setGeometry(QtCore.QRect(471, 370, 41, 28))
        self.Hidepassword.setStyleSheet("background-color: none;")
        self.Hidepassword.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/iconLogin/hide_icon_183908.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Hidepassword.setIcon(icon)
        self.Hidepassword.setObjectName("Hidepassword")
        self.Showpassword = QtWidgets.QPushButton(self.widget)
        self.Showpassword.setGeometry(QtCore.QRect(471, 370, 41, 28))
        self.Showpassword.setStyleSheet("background-color: none;")
        self.Showpassword.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/iconLogin/show_icon_183921.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Showpassword.setIcon(icon1)
        self.Showpassword.setObjectName("Showpassword")
    
        #dashboard client
        self.dashboard = QtWidgets.QWidget(App)
        self.dashboard.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.dashboard.setStyleSheet("background-color: none;")
        self.dashboard.setObjectName("dashboard")
        self.widget1 = QtWidgets.QWidget(self.dashboard)
        self.widget1.setGeometry(QtCore.QRect(0, 20, 501, 1080))
        self.widget1.setStyleSheet("background-color: #D9D9D9;")
        self.widget1.setObjectName("widget")
        self.helloText = QtWidgets.QLabel(self.widget1)
        self.helloText.setGeometry(QtCore.QRect(38, 45, 422, 73))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.helloText.setFont(font)
        self.helloText.setStyleSheet("background-color: #AAAAAA;\n"
"border-radius:25px;")
        self.helloText.setAlignment(QtCore.Qt.AlignCenter)
        self.helloText.setObjectName("helloText")
        self.nameInfor = QtWidgets.QLabel(self.widget1)
        self.nameInfor.setGeometry(QtCore.QRect(38, 170, 422, 73))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nameInfor.setFont(font)
        self.nameInfor.setStyleSheet("background-color: #AAAAAA;\n"
"border-radius:25px;")
        self.nameInfor.setAlignment(QtCore.Qt.AlignCenter)
        self.nameInfor.setObjectName("nameInfor")
        self.dateofbirthInfor = QtWidgets.QLabel(self.widget1)
        self.dateofbirthInfor.setGeometry(QtCore.QRect(38, 295, 422, 73))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateofbirthInfor.setFont(font)
        self.dateofbirthInfor.setStyleSheet("background-color: #AAAAAA;\n"
"border-radius:25px;")
        self.dateofbirthInfor.setAlignment(QtCore.Qt.AlignCenter)
        self.dateofbirthInfor.setObjectName("dateofbirthInfor")
        self.logoutButton = QtWidgets.QPushButton(self.widget1)
        self.logoutButton.setGeometry(QtCore.QRect(38, 860, 422, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("background-color: #78A9CA;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:25px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-logout-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon)
        self.logoutButton.setObjectName("logoutButton")
        self.fieldListbtn = QtWidgets.QWidget(self.dashboard)
        self.fieldListbtn.setGeometry(QtCore.QRect(500, 20, 1421, 1080))
        self.fieldListbtn.setStyleSheet("background-color: #656464;")
        self.fieldListbtn.setObjectName("fieldListbtn")
        self.btnlListcam_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnlListcam_icon.setGeometry(QtCore.QRect(90, 50, 321, 161))
        self.btnlListcam_icon.setStyleSheet("background-color:none;")
        self.btnlListcam_icon.setObjectName("btnlListcam_icon")
        self.listcamPage = QtWidgets.QPushButton(self.btnlListcam_icon)
        self.listcamPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.listcamPage.setFont(font)
        self.listcamPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.listcamPage.setObjectName("listcamPage")
        self.iconListcambtn = QtWidgets.QPushButton(self.btnlListcam_icon)
        self.iconListcambtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconListcambtn.setStyleSheet("background-color:#35B4F9;\n"
"border-radius:25px")
        self.iconListcambtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-list-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconListcambtn.setIcon(icon1)
        self.iconListcambtn.setIconSize(QtCore.QSize(24, 24))
        self.iconListcambtn.setObjectName("iconListcambtn")
        self.btnlListvideovolation_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnlListvideovolation_icon.setGeometry(QtCore.QRect(550, 50, 321, 161))
        self.btnlListvideovolation_icon.setStyleSheet("background-color:none;")
        self.btnlListvideovolation_icon.setObjectName("btnlListvideovolation_icon")
        self.videoviolationPage = QtWidgets.QPushButton(self.btnlListvideovolation_icon)
        self.videoviolationPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.videoviolationPage.setFont(font)
        self.videoviolationPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.videoviolationPage.setObjectName("videoviolationPage")
        self.iconListvideoviolationbtn = QtWidgets.QPushButton(self.btnlListvideovolation_icon)
        self.iconListvideoviolationbtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconListvideoviolationbtn.setStyleSheet("background-color:rgb(255, 0, 0);\n"
"border-radius:25px")
        self.iconListvideoviolationbtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-cinema-44.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconListvideoviolationbtn.setIcon(icon2)
        self.iconListvideoviolationbtn.setIconSize(QtCore.QSize(28, 28))
        self.iconListvideoviolationbtn.setObjectName("iconListvideoviolationbtn")
        self.btnlChart_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnlChart_icon.setGeometry(QtCore.QRect(1010, 50, 321, 161))
        self.btnlChart_icon.setStyleSheet("background-color:none;")
        self.btnlChart_icon.setObjectName("btnlChart_icon")
        self.ChartPage = QtWidgets.QPushButton(self.btnlChart_icon)
        self.ChartPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ChartPage.setFont(font)
        self.ChartPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.ChartPage.setObjectName("ChartPage")
        self.iconChartbtn = QtWidgets.QPushButton(self.btnlChart_icon)
        self.iconChartbtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconChartbtn.setStyleSheet("background-color:#00CD21;\n"
"border-radius:25px")
        self.iconChartbtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-histogram-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconChartbtn.setIcon(icon3)
        self.iconChartbtn.setIconSize(QtCore.QSize(28, 28))
        self.iconChartbtn.setObjectName("iconChartbtn")
        self.btnCreateaccout_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnCreateaccout_icon.setGeometry(QtCore.QRect(90, 260, 321, 161))
        self.btnCreateaccout_icon.setStyleSheet("background-color:none;")
        self.btnCreateaccout_icon.setObjectName("btnCreateaccout_icon")
        self.createaccountPage = QtWidgets.QPushButton(self.btnCreateaccout_icon)
        self.createaccountPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.createaccountPage.setFont(font)
        self.createaccountPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.createaccountPage.setObjectName("createaccountPage")
        self.iconCreateaccountbtn = QtWidgets.QPushButton(self.btnCreateaccout_icon)
        self.iconCreateaccountbtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconCreateaccountbtn.setStyleSheet("background-color:rgb(44, 83, 255);\n"
"border-radius:25px;\n"
"")
        self.iconCreateaccountbtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-add-user-male-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconCreateaccountbtn.setIcon(icon4)
        self.iconCreateaccountbtn.setIconSize(QtCore.QSize(28, 28))
        self.iconCreateaccountbtn.setObjectName("iconCreateaccountbtn")
        self.frame = QtWidgets.QFrame(self.dashboard)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 1921, 26))
        self.frame.setStyleSheet("background-color: rgb(90,90,90);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget_7 = QtWidgets.QWidget(self.frame)
        self.widget_7.setGeometry(QtCore.QRect(1830, 0, 81, 26))
        self.widget_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:12px;")
        self.widget_7.setObjectName("widget_7")
        self.MinimunBtn = QtWidgets.QPushButton(self.widget_7)
        self.MinimunBtn.setGeometry(QtCore.QRect(10, 1, 24, 24))
        self.MinimunBtn.setStyleSheet("background-color: rgb(140,140,140);\n"
"border-radius:12px")
        self.MinimunBtn.setText("")
        iconMin = QtGui.QIcon()
        iconMin.addPixmap(QtGui.QPixmap("static/icon/minimum-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MinimunBtn.setIcon(iconMin)
        self.MinimunBtn.setObjectName("MinimunBtn")
        self.CloseBtn = QtWidgets.QPushButton(self.widget_7)
        self.CloseBtn.setGeometry(QtCore.QRect(50, 1, 24, 24))
        self.CloseBtn.setStyleSheet("background-color: rgb(239, 0, 0);\n"
"border-radius:12px")
        self.CloseBtn.setText("")
        iconClose = QtGui.QIcon()
        iconClose.addPixmap(QtGui.QPixmap("static/icon/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseBtn.setIcon(iconClose)
        self.CloseBtn.setObjectName("CloseBtn")
        
        #sidebar
        self.centralapp = QtWidgets.QWidget(App)
        self.centralapp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralapp.setObjectName("centralapp")
        self.centralapp.setGeometry(0,0,1920,1080)
        self.gridLayout = QtWidgets.QGridLayout(self.centralapp)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listpage = QtWidgets.QWidget(self.centralapp)
        self.listpage.setObjectName("listpage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.listpage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_s = QtWidgets.QWidget(self.listpage)
        self.widget_s.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_s.setStyleSheet("border:none;")
        self.widget_s.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_s)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.search = QtWidgets.QHBoxLayout()
        self.search.setSpacing(10)
        self.search.setObjectName("search")
        
        self.search_input = QtWidgets.QLineEdit(self.widget_s)
        self.search_input.setStyleSheet("QLineEdit{\n"
# "    border: none;\n"
"    padding: 5px 10px;\n"
"}\n"
"QLineEdit::focus{\n"
"background-color: #70B9FE;\n"
"};")
        self.search_input.setText("")
        self.search_input.setObjectName("search_input")
        self.search.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.widget_s)
        self.search_btn.setStyleSheet("border:none;")
        self.search_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/iconDashboard/search-13-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon)
        self.search_btn.setObjectName("search_btn")
        self.search.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.search)
        spacerItem1 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.user_btn = QtWidgets.QPushButton(self.widget_s)
        self.user_btn.setStyleSheet("border:none;")
        self.user_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/iconDashboard/user-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon1)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_4.addWidget(self.user_btn)
        self.verticalLayout_5.addWidget(self.widget_s)
        self.stackedWidget = QtWidgets.QStackedWidget(self.listpage)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.homepage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.homepage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.homepage)
        self.dashboardpage = QtWidgets.QWidget()
        self.dashboardpage.setObjectName("dashboardpage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dashboardpage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.dashboardpage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dashboardpage)
        self.listcampage = QtWidgets.QWidget()
        self.listcampage.setObjectName("listcampage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.listcampage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.listcampage)
        # font = QtGui.QFont()
        # font.setPointSize(20)
        # self.label_6.setFont(font)
        # self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_6.setObjectName("label_6")
        self.widget_campage = QtWidgets.QWidget(self.listcampage)
        self.widget_campage.setStyleSheet("background-color:#656464")
        self.widget_campage.setObjectName("widget_campage")
        
        self.listWidget_addcam = QtWidgets.QListWidget(self.widget_campage)
        self.listWidget_addcam.setGeometry(QtCore.QRect(0, 40, 256, 978))
        self.listWidget_addcam.setStyleSheet("background-color:rgb(217,217,217);")
        self.listWidget_addcam.setObjectName("listWidget_addcam")
        self.listWidget_addcam.setSpacing(20)
        self.listcamera = QtWidgets.QWidget(self.widget_campage)
        self.listcamera.setGeometry(QtCore.QRect(0, 0, 255, 40))
        self.listcamera.setStyleSheet("background-color:#b4b4b4")
        self.listcamera.setObjectName("listcamera")
        self.label_listcam = QtWidgets.QLabel(self.listcamera)
        self.label_listcam.setGeometry(QtCore.QRect(50, 14, 111, 16))
        self.label_listcam.setAlignment(QtCore.Qt.AlignCenter)
        self.label_listcam.setObjectName("label_listcam")
        self.openaddcam_btn = QtWidgets.QPushButton(self.listcamera)
        self.openaddcam_btn.setToolTip("Tạo thêm camera")
        self.openaddcam_btn.setGeometry(QtCore.QRect(170, 13, 30, 20))
        self.openaddcam_btn.setStyleSheet("border:none;")
        self.openaddcam_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/iconSetupcam/4115237-add-plus_114047.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openaddcam_btn.setIcon(icon2)
        self.openaddcam_btn.setObjectName("openaddcam_btn")
        self.removecam_btn = QtWidgets.QPushButton(self.listcamera)
        self.removecam_btn.setGeometry(QtCore.QRect(200, 13, 31, 20))
        self.removecam_btn.setStyleSheet("border:none;")
        self.removecam_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/iconSetupcam/subtract_icon_216960.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removecam_btn.setIcon(icon3)
        self.removecam_btn.setObjectName("removecam_btn")
        self.widget_addcam = QtWidgets.QWidget(self.widget_campage)
        self.widget_addcam.setGeometry(QtCore.QRect(275, 0, 1431, 1018))
        self.widget_addcam.setStyleSheet("background-color:#f2f2f2")
        self.widget_addcam.setObjectName("widget_addcam")
        self.lcam = QtWidgets.QWidget(self.widget_addcam)
        self.lcam.setGeometry(QtCore.QRect(235, 130, 961, 41))
        self.lcam.setObjectName("lcam")
        self.lcam.setStyleSheet(
                "background-color:#d9d9d9;\n"
"border-radius:20px;\n"
        )
        self.linkcam_input = QtWidgets.QLineEdit(self.lcam)
        self.linkcam_input.setGeometry(QtCore.QRect(110, 0, 851, 40))
        self.linkcam_input.setStyleSheet("background-color:#d9d9d9;\n"
"border-radius:20px;\n"
"padding-left:70px")
        self.linkcam_input.setCursorPosition(0)
        self.linkcam_input.setObjectName("linkcam_input")
        self.label_linkcam = QtWidgets.QLabel(self.lcam)
        self.label_linkcam.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_linkcam.setFont(font)
        self.label_linkcam.setStyleSheet("background-color:none;")
        self.label_linkcam.setObjectName("label_linkcam")
        self.ncam = QtWidgets.QWidget(self.widget_addcam)
        self.ncam.setGeometry(QtCore.QRect(235, 210, 961, 41))
        self.ncam.setStyleSheet("background-color:#d9d9d9;\n"
"border-radius:20px;")
        self.ncam.setObjectName("ncam")
        self.namecam_inout = QtWidgets.QLineEdit(self.ncam)
        self.namecam_inout.setGeometry(QtCore.QRect(110, 0, 851, 40))
        self.namecam_inout.setStyleSheet("background-color:#d9d9d9;\n"
"border-radius:20px;\n"
"padding-left:70px")
        self.namecam_inout.setCursorPosition(0)
        self.namecam_inout.setObjectName("namecam_inout")
        self.label_namecam = QtWidgets.QLabel(self.ncam)
        self.label_namecam.setGeometry(QtCore.QRect(10, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_namecam.setFont(font)
        self.label_namecam.setStyleSheet("background-color:none;")
        self.label_namecam.setObjectName("label_namecam")
        self.Inforcam = QtWidgets.QWidget(self.widget_addcam)
        self.Inforcam.setGeometry(QtCore.QRect(235, 300, 961, 251))
        self.Inforcam.setObjectName("Inforcam")
        self.label_locationcam = QtWidgets.QLabel(self.Inforcam)
        self.label_locationcam.setGeometry(QtCore.QRect(40, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_locationcam.setFont(font)
        self.label_locationcam.setStyleSheet("background-color:#d9d9d9;\n"
"border-radius:15px;")
        self.label_locationcam.setAlignment(QtCore.Qt.AlignCenter)
        self.label_locationcam.setObjectName("label_locationcam")
        self.widget_distric = QtWidgets.QWidget(self.Inforcam)
        self.widget_distric.setGeometry(QtCore.QRect(140, 110, 221, 51))
        self.widget_distric.setStyleSheet("background-color:#d9d9d9;\n"
"border-radius:20px;")
        self.widget_distric.setObjectName("widget_distric")
        self.label_district = QtWidgets.QLabel(self.widget_distric)
        self.label_district.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.label_district.setAlignment(QtCore.Qt.AlignCenter)
        self.label_district.setObjectName("label_district")
        self.district_input = QtWidgets.QLineEdit(self.widget_distric)
        self.district_input.setGeometry(QtCore.QRect(72, 1, 141, 51))
        self.district_input.setObjectName("district_input")
        self.widget_wards = QtWidgets.QWidget(self.Inforcam)
        self.widget_wards.setGeometry(QtCore.QRect(480, 110, 221, 51))
        self.widget_wards.setStyleSheet("background-color:#d9d9d9;\n"
"border-radius:20px;")
        self.widget_wards.setObjectName("widget_wards")
        self.label_wards = QtWidgets.QLabel(self.widget_wards)
        self.label_wards.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.label_wards.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wards.setObjectName("label_wards")
        self.wards_input = QtWidgets.QLineEdit(self.widget_wards)
        self.wards_input.setGeometry(QtCore.QRect(72, 0, 141, 51))
        self.wards_input.setObjectName("wards_input")
        self.addcam_btn = QtWidgets.QPushButton(self.widget_addcam)
        self.addcam_btn.setGeometry(QtCore.QRect(490, 650, 171, 51))
        self.addcam_btn.setStyleSheet("background-color:#82D2FE;\n"
"border:none;\n"
"border-radius:20px;")
        self.addcam_btn.setObjectName("addcam_btn")
        self.preview_btn = QtWidgets.QPushButton(self.widget_addcam)
        self.preview_btn.setGeometry(QtCore.QRect(730, 650, 171, 51))
        self.preview_btn.setStyleSheet("background-color:#82D2FE;\n"
"border:none;\n"
"border-radius:20px;")
        self.preview_btn.setObjectName("preview_btn")
        self.gridLayout_4.addWidget(self.widget_campage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.listcampage)
        self.vidviolationpage = QtWidgets.QWidget()
        self.vidviolationpage.setObjectName("vidviolationpage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.vidviolationpage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        # self.label_7 = QtWidgets.QLabel(self.vidviolationpage)
        # font = QtGui.QFont()
        # font.setPointSize(20)
        # self.label_7.setFont(font)
        # self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_7.setObjectName("label_7")
        self.listviolation = QListWidget(self.vidviolationpage)
        self.listviolation.setGeometry(0,0,1080,1054)
        self.listviolation.setSpacing(20)
        self.listviolation.setStyleSheet("background-color: none;\n"
    "")
        self.gridLayout_5.addWidget(self.listviolation, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.vidviolationpage)
        self.statisticpage = QtWidgets.QWidget()
        self.statisticpage.setObjectName("statisticpage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.statisticpage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.statisticpage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.statisticpage)
        self.searchpage = QtWidgets.QWidget()
        self.searchpage.setObjectName("searchpage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.searchpage)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.searchpage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.searchpage)
        self.userpage = QtWidgets.QWidget()
        self.userpage.setObjectName("userpage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.userpage)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_userpage = QtWidgets.QWidget(self.userpage)
        self.widget_userpage.setStyleSheet("background-color: rgb(117, 117, 117)")
        self.widget_userpage.setObjectName("widget_userpage")
        self.avatar = QtWidgets.QWidget(self.widget_userpage)
        self.avatar.setGeometry(QtCore.QRect(40, 40, 220, 220))
        self.avatar.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius:3px")
        self.avatar.setObjectName("avatar")
        self.img = QtWidgets.QLabel(self.avatar)
        self.img.setGeometry(QtCore.QRect(50, 30, 120, 120))
        self.img.setMinimumSize(QtCore.QSize(120, 0))
        self.img.setAutoFillBackground(False)
        self.img.setStyleSheet("border: 2px solid rgb(255,255,255);\n"
"border-radius:60px\n"
"")
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap(".\\../5043918.png"))
        self.img.setScaledContents(True)
        self.img.setAlignment(QtCore.Qt.AlignCenter)
        self.img.setWordWrap(False)
        self.img.setObjectName("img")
        self.nameuser = QtWidgets.QLabel(self.avatar)
        self.nameuser.setGeometry(QtCore.QRect(60, 160, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nameuser.setFont(font)
        self.nameuser.setStyleSheet("border:none;\n"
"color:rgb(255,255,255);\n"
"")
        self.nameuser.setAlignment(QtCore.Qt.AlignCenter)
        self.nameuser.setObjectName("nameuser")
        self.information = QtWidgets.QWidget(self.widget_userpage)
        self.information.setGeometry(QtCore.QRect(300, 40, 410, 440))
        self.information.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius:3px")
        self.information.setObjectName("information")
        self.FullName = QtWidgets.QWidget(self.information)
        self.FullName.setGeometry(QtCore.QRect(60, 30, 290, 80))
        self.FullName.setStyleSheet("border-radius:5px")
        self.FullName.setObjectName("FullName")
        self.label_name = QtWidgets.QLabel(self.FullName)
        self.label_name.setGeometry(QtCore.QRect(10, 5, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_name.setFont(font)
        self.label_name.setGeometry(QtCore.QRect(35, 40, 220, 31))
        self.label_name.setStyleSheet("border:none;\n"
"color:rgb(255,255,255)")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.nametxt = QtWidgets.QLabel(self.FullName)
        self.nametxt.setGeometry(QtCore.QRect(35, 40, 220, 31))
        self.nametxt.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.nametxt.setObjectName("nametxt")
        self.date = QtWidgets.QWidget(self.information)
        self.date.setGeometry(QtCore.QRect(60, 130, 290, 80))
        self.date.setStyleSheet("border-radius:5px")
        self.date.setObjectName("date")
        self.label_date = QtWidgets.QLabel(self.date)
        self.label_date.setGeometry(QtCore.QRect(10, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("border:none;\n"
"color:rgb(255,255,255)")
        self.label_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.datetxt = QtWidgets.QLabel(self.date)
        self.datetxt.setGeometry(QtCore.QRect(35, 40, 220, 31))
        self.datetxt.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.datetxt.setObjectName("datetxt")
        self.Emailinfor = QtWidgets.QWidget(self.information)
        self.Emailinfor.setGeometry(QtCore.QRect(60, 230, 290, 80))
        self.Emailinfor.setStyleSheet("border-radius:5px")
        self.Emailinfor.setObjectName("Emailinfor")
        self.label_email = QtWidgets.QLabel(self.Emailinfor)
        self.label_email.setGeometry(QtCore.QRect(10, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("border:none;\n"
"color:rgb(255,255,255)")
        self.label_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_email.setObjectName("label_email")
        self.emailtxt = QtWidgets.QLabel(self.Emailinfor)
        self.emailtxt.setGeometry(QtCore.QRect(35, 40, 220, 31))
        self.emailtxt.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.emailtxt.setObjectName("emailtxt")
        self.phonenumber = QtWidgets.QWidget(self.information)
        self.phonenumber.setGeometry(QtCore.QRect(60, 330, 290, 80))
        self.phonenumber.setStyleSheet("border-radius:5px")
        self.phonenumber.setObjectName("phonenumber")
        self.label_nphone = QtWidgets.QLabel(self.phonenumber)
        self.label_nphone.setGeometry(QtCore.QRect(10, 5, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nphone.setFont(font)
        self.label_nphone.setStyleSheet("border:none;\n"
"color:rgb(255,255,255)")
        self.label_nphone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_nphone.setObjectName("label_nphone")
        self.nphonetxt = QtWidgets.QLabel(self.phonenumber)
        self.nphonetxt.setGeometry(QtCore.QRect(35, 40, 220, 31))
        self.nphonetxt.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.nphonetxt.setObjectName("nphonetxt")
        self.logout_btn = QtWidgets.QPushButton(self.widget_userpage)
        self.logout_btn.setGeometry(QtCore.QRect(70, 420, 160, 31))
        self.logout_btn.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.logout_btn.setObjectName("logout_btn")
        self.changeinfor_btn = QtWidgets.QPushButton(self.widget_userpage)
        self.changeinfor_btn.setGeometry(QtCore.QRect(70, 360, 160, 31))
        self.changeinfor_btn.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.changeinfor_btn.setObjectName("changeinfor_btn")
        self.gridLayout_8.addWidget(self.widget_userpage, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.userpage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.listpage, 0, 1, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralapp)
        self.full_menu_widget.setContentsMargins(25,0,25,15)
        self.full_menu_widget.setMinimumWidth(320)
        self.full_menu_widget.setStyleSheet("background-color: 	#383838;\n"
"QPushButton#pushButton{\n"
"border:none;\n"
"border-radius: 3px;\n"
"text-align: left;\n"
"padding: 8px 0 8px 15px;\n"
"color: #788596;\n"
"background-color:rgb(235, 237, 239);\n"
"};\n"
"\n"
"QPushButton#pushButton:hover {\n"
"        background-color: rgb(235, 237, 239);\n"
"};\n"
"QPushButton#pushButton:checked {\n"
"        background-color: rgb(235, 237, 239);\n"
"}")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.appname = QtWidgets.QHBoxLayout()
        self.appname.setSpacing(0)
        self.appname.setObjectName("appname")
        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setFamily('Candara')
        font_nameapp = QtGui.QFont()
        font_nameapp.setPointSize(13)
        font.setFamily("Rockwell Condensed")
        self.logo_label_3.setFont(font_nameapp)
        self.logo_label_3.setStyleSheet("color: rgb(255, 255, 255);""    background-color:rgb(10, 0, 150);\n""border-radius:10px;")
        self.logo_label_3.setObjectName("logo_label_3")
        self.logo_label_3.setMinimumHeight(50)
        self.logo_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.appname.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.appname)
        self.sidebar = QtWidgets.QVBoxLayout()
        self.sidebar.setContentsMargins(0,10,0,0)
        self.sidebar.setSpacing(10)
        self.sidebar.setObjectName("sidebar")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dashborad_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.dashborad_btn_2.setFont(font)
        # self.dashborad_btn_2.setContentsMargins(20,0,0,0)
        self.dashborad_btn_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 3px;\n"
"text-align: left;\n"
"padding: 8px 0 8px 15px;\n"
"background-color: none;\n"
"color:#9da5b1;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::checked{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}")
        icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap("static/iconDashboard/dashboard-48 (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("static/iconDashboard/dashboard-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashborad_btn_2.setIcon(icon3)
        self.dashborad_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.dashborad_btn_2.setCheckable(True)
        self.dashborad_btn_2.setAutoExclusive(True)
        self.dashborad_btn_2.setObjectName("dashborad_btn_2")
        self.sidebar.addWidget(self.dashborad_btn_2)
        self.listcam_btn_menu = QtWidgets.QPushButton(self.full_menu_widget)
        
        self.listcam_btn_menu.setStyleSheet(
              "QPushButton{\n"
"border:none;\n"
"border-radius: 3px;\n"
"text-align: left;\n"
"padding: 8px 0 8px 15px;\n"
"background-color: none;\n"
"color:#9da5b1;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::checked{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}"
        )
        icon4 = QtGui.QIcon()
        # icon4.addPixmap(QtGui.QPixmap("static/iconDashboard/activity-feed-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("static/iconDashboard/activity-feed-48 (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.listcam_btn_menu.setIcon(icon4)
        self.listcam_btn_menu.setFont(font)
        self.listcam_btn_menu.setIconSize(QtCore.QSize(20, 20))
        self.listcam_btn_menu.setCheckable(True)
        self.listcam_btn_menu.setAutoExclusive(True)
        self.listcam_btn_menu.setObjectName("listcam_btn_menu")
        
        self.sidebar.addWidget(self.listcam_btn_menu)
        self.videoviolation_btn_menu = QtWidgets.QPushButton(self.full_menu_widget)
        self.videoviolation_btn_menu.setContentsMargins(5,0,0,0)
        self.videoviolation_btn_menu.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 3px;\n"
"text-align: left;\n"
"padding: 8px 0 8px 15px;\n"
"background-color: none;\n"
"color:#9da5b1;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::checked{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}")
        icon5 = QtGui.QIcon()
        # icon5.addPixmap(QtGui.QPixmap("static/iconDashboard/video-play-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("static/iconDashboard/video-play-4-48 (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.videoviolation_btn_menu.setIcon(icon5)
        self.videoviolation_btn_menu.setFont(font)
        self.videoviolation_btn_menu.setIconSize(QtCore.QSize(20, 20))
        self.videoviolation_btn_menu.setCheckable(True)
        self.videoviolation_btn_menu.setAutoExclusive(True)
        self.videoviolation_btn_menu.setObjectName("videoviolation_btn_menu")
        self.sidebar.addWidget(self.videoviolation_btn_menu)
        self.statistic_btn_menu = QtWidgets.QPushButton(self.full_menu_widget)
        self.statistic_btn_menu.setFont(font)
        self.statistic_btn_menu.setContentsMargins(5,0,0,0)
        self.statistic_btn_menu.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 3px;\n"
"text-align: left;\n"
"padding: 8px 0 8px 15px;\n"
"background-color: none;\n"
"color:#9da5b1;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::checked{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}")
        icon6 = QtGui.QIcon()
        # icon6.addPixmap(QtGui.QPixmap("static/iconDashboard/bar-chart-5-48 (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("static/iconDashboard/bar-chart-5-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.statistic_btn_menu.setIcon(icon6)
        self.statistic_btn_menu.setIconSize(QtCore.QSize(20, 20))
        self.statistic_btn_menu.setCheckable(True)
        self.statistic_btn_menu.setAutoExclusive(True)
        self.statistic_btn_menu.setObjectName("statistic_btn_menu")
        self.sidebar.addWidget(self.statistic_btn_menu)
        self.verticalLayout_4.addLayout(self.sidebar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius: 3px;\n"
"text-align: left;\n"
"padding: 8px 0 8px 15px;\n"
"background-color: none;\n"
"color:#9da5b1;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}\n"
"QPushButton::checked{\n"
"    background-color:    rgba(235, 237, 239,0.3);\n"
"    color:#ffffff;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("static/iconDashboard/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit_btn_2.setIcon(icon7)
        self.exit_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 0, 1, 1)
        #setup camera
        self.widget_setupcam = QtWidgets.QWidget(self.widget_campage)
        self.widget_setupcam.setGeometry(QtCore.QRect(255, 0, 1343, 1018))
        self.widget_setupcam.setStyleSheet("background-color:#f2f2f2")
        self.widget_setupcam.setObjectName("widget_setupcam")
        self.Draw = QtWidgets.QWidget(self.widget_setupcam)
        self.Draw.setGeometry(0,0,1344,800)
        self.Draw.setStyleSheet("QWidget {\n"
"background-color: rgb(120, 169, 202);\n"
"}")
        self.Draw.setContentsMargins(10,10,0,0)
        self.Draw.setObjectName("Draw")
        self.Save_draw = QtWidgets.QPushButton(self.Draw)
        self.Save_draw.setToolTip("Lưu cài đặt")
        self.Save_draw.setGeometry(QtCore.QRect(750,750, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Save_draw.setFont(font)
        self.Save_draw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save_draw.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Save_draw.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/icon/save-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save_draw.setIcon(icon1)
        self.Save_draw.setIconSize(QtCore.QSize(24, 24))
        self.Save_draw.setAutoRepeat(False)
        self.Save_draw.setAutoExclusive(False)
        self.Save_draw.setFlat(False)
        self.Save_draw.setObjectName("Save_draw")

#draw left line 1:->
        self.Line_left = QtWidgets.QPushButton(self.Draw)
        self.Line_left.setGeometry(QtCore.QRect(30,750, 41, 41))
        self.Line_left.setToolTip("Vẽ làn đường trái")
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line_left.setFont(font)
        self.Line_left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line_left.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line_left.setText("")
#icon draw line left 1: start
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/icon/left-land-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line_left.setIcon(icon1)
        self.Line_left.setIconSize(QtCore.QSize(24, 24))
        self.Line_left.setAutoRepeat(False)
        self.Line_left.setAutoExclusive(False)
        self.Line_left.setFlat(False)
        self.Line_left.setObjectName("Line_left")
##left line 1 <--
        self.Square = QtWidgets.QPushButton(self.Draw)
        self.Square.setToolTip("Chọn đèn giao thông")
        self.Square.setGeometry(QtCore.QRect(350,750, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Square.setFont(font)
        self.Square.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Square.setStyleSheet("QPushButton#Square:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Square:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Square {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Square.setText("")
#icon choose traffic_light
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/icon/crect-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Square.setIcon(icon2)
        self.Square.setIconSize(QtCore.QSize(24, 24))
        self.Square.setAutoRepeat(False)
        self.Square.setAutoExclusive(False)
        self.Square.setFlat(False)
        self.Square.setObjectName("Square")
        self.Draw_line = QtWidgets.QWidget(self.Draw)
        self.Draw_line.setGeometry(QtCore.QRect(23, 20, 1281, 720))
        self.Draw_line.setStyleSheet("QWidget {\n"
"        background-color: rgb(62, 62, 62);\n"
"}")
        self.Draw_line.setObjectName("Draw_line")

# go back previous activity
        self.Delete = QtWidgets.QPushButton(self.Draw)
        self.Delete.setToolTip("Hoàn tác")
        self.Delete.setGeometry(QtCore.QRect(820,750, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Delete.setFont(font)
        self.Delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete.setStyleSheet("QPushButton#Delete:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton#Delete:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton#Delete {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Delete.setText("")
#icon back draw previous
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/icon/back-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete.setIcon(icon3)
        self.Delete.setIconSize(QtCore.QSize(24, 24))
        self.Delete.setAutoRepeat(False)
        self.Delete.setAutoExclusive(False)
        self.Delete.setFlat(False)
        self.Delete.setObjectName("Delete")


#draw line center 1 : -->
        self.Line_Center = QtWidgets.QPushButton(self.Draw)
        self.Line_Center.setGeometry(QtCore.QRect(80,750, 41, 41))
        self.Line_Center.setToolTip("Vẽ làn đường giữa")
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line_Center.setFont(font)
        self.Line_Center.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line_Center.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line_Center.setText("")
#icon draw line Center 1: start
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/icon/center-land-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line_Center.setIcon(icon4)
        self.Line_Center.setIconSize(QtCore.QSize(24, 24))
        self.Line_Center.setAutoRepeat(False)
        self.Line_Center.setAutoExclusive(False)
        self.Line_Center.setFlat(False)
        self.Line_Center.setObjectName("Line_Center")
#draw line center 1 <--

#right line 1-->
        self.Line_Right = QtWidgets.QPushButton(self.Draw)
        self.Line_Right.setToolTip("Vẽ làn đường phải")
        self.Line_Right.setGeometry(QtCore.QRect(130,750, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line_Right.setFont(font)
        self.Line_Right.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line_Right.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line_Right.setText("")
#icon draw line right 1: start
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("static/icon/right-land-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line_Right.setIcon(icon5)
        self.Line_Right.setIconSize(QtCore.QSize(24, 24))
        self.Line_Right.setAutoRepeat(False)
        self.Line_Right.setAutoExclusive(False)
        self.Line_Right.setFlat(False)
        self.Line_Right.setObjectName("Line_Right")


#line center 2: end -->
        self.Line_Center_2 = QtWidgets.QPushButton(self.Draw)
        self.Line_Center_2.setToolTip("Vẽ hướng đi thẳng")
        self.Line_Center_2.setGeometry(QtCore.QRect(250,750, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line_Center_2.setFont(font)
        self.Line_Center_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line_Center_2.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line_Center_2.setText("")
#icon draw line center 2 : end 
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("static/icon/keep-forward-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line_Center_2.setIcon(icon6)
        self.Line_Center_2.setIconSize(QtCore.QSize(24, 24))
        self.Line_Center_2.setAutoRepeat(False)
        self.Line_Center_2.setAutoExclusive(False)
        self.Line_Center_2.setFlat(False)
        self.Line_Center_2.setObjectName("Line_Center_2")

# line left 2:end -->
        self.Line_left_2 = QtWidgets.QPushButton(self.Draw)
        self.Line_left_2.setGeometry(QtCore.QRect(200,750, 41, 41))
        self.Line_left_2.setToolTip("Vẽ hướng rẽ trái")
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line_left_2.setFont(font)
        self.Line_left_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line_left_2.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line_left_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("static/icon/turn-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line_left_2.setIcon(icon7)
        self.Line_left_2.setIconSize(QtCore.QSize(24, 24))
        self.Line_left_2.setAutoRepeat(False)
        self.Line_left_2.setAutoExclusive(False)
        self.Line_left_2.setFlat(False)
        self.Line_left_2.setObjectName("Line_left_2")


#line right 2 : end -->
        self.Line_Right_2 = QtWidgets.QPushButton(self.Draw)
        self.Line_Right_2.setGeometry(QtCore.QRect(300,750, 41, 41))
        self.Line_Right_2.setToolTip("Vẽ hướng rẽ phải")
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Line_Right_2.setFont(font)
        self.Line_Right_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Line_Right_2.setStyleSheet("QPushButton:disabled {\n"
"     background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.273, stop:0.0170455 rgba(118, 0, 0, 255), stop:0.727273 rgba(61, 0, 0, 255));\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 15, 43, 255), stop:1 rgba(36, 115, 173, 255));\n"
"}\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 106, 147, 255), stop:1 rgba(50, 169, 255, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Line_Right_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("static/icon/turn-right-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Line_Right_2.setIcon(icon8)
        self.Line_Right_2.setIconSize(QtCore.QSize(24, 24))
        self.Line_Right_2.setAutoRepeat(False)
        self.Line_Right_2.setAutoExclusive(False)
        self.Line_Right_2.setFlat(False)
        self.Line_Right_2.setObjectName("Line_Right_2")
## line right 2 :<--
        self.Square.raise_()
        self.Draw_line.raise_()
        self.Delete.raise_()
        self.Line_Center.raise_()
        self.Line_Right.raise_()
        self.Line_left.raise_()
        self.Line_Center_2.raise_()
        self.Line_left_2.raise_()
        self.Line_Right_2.raise_()
        self.Save_draw.raise_()
#setup rule:
        # self.line = QtWidgets.QFrame(self.widget_setupcam)
        # self.line.setGeometry(QtCore.QRect(482, 10, 16, 491))
        # self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.line.setMidLineWidth(0)
        # self.line.setFrameShape(QtWidgets.QFrame.VLine)
        # self.line.setObjectName("line")

        self.tabWidget = QtWidgets.QTabWidget(self.widget_setupcam)
        self.tabWidget.setGeometry(QtCore.QRect(20, 850, 500, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab { \n"
"height: 20px; \n"
"width: 80px;\n"
"background-color:  rgb(90, 90, 90);\n"
"border-top-right-radius : 5px;\n"
"border-top-left-radius : 5px;\n"
"color: #fff;\n"
"\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"border: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: #d9d9d9;\n"
"color: #000;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"background-color: #d9d9d9;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.left_lane = QtWidgets.QWidget()
        self.left_lane.setStyleSheet("QWidget {\n"
"background-color: #d9d9d9;\n"
"}")
        self.left_lane.setObjectName("left_lane")
        self.turn_left_left_lane = QtWidgets.QCheckBox(self.left_lane)
        self.turn_left_left_lane.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.turn_left_left_lane.setObjectName("turn_left_left_lane")
        self.go_forward_left_lane = QtWidgets.QCheckBox(self.left_lane)
        self.go_forward_left_lane.setGeometry(QtCore.QRect(140, 20, 91, 17))
        self.go_forward_left_lane.setObjectName("go_forward_left_lane")
        self.turn_right_left_lane = QtWidgets.QCheckBox(self.left_lane)
        self.turn_right_left_lane.setGeometry(QtCore.QRect(260, 20, 91, 17))
        self.turn_right_left_lane.setObjectName("turn_right_left_lane")
        self.red_light_left = QtWidgets.QCheckBox(self.left_lane)
        self.red_light_left.setGeometry(QtCore.QRect(380, 20, 90, 17))
        self.red_light_left.setObjectName("red_light_left")
        self.tabWidget.addTab(self.left_lane, "")
        self.center_lane = QtWidgets.QWidget()
        self.center_lane.setStyleSheet("QWidget {\n"
"background-color: #d9d9d9;\n"
"}")
        self.center_lane.setObjectName("center_lane")
        self.turn_right_center_lane = QtWidgets.QCheckBox(self.center_lane)
        self.turn_right_center_lane.setGeometry(QtCore.QRect(260, 20, 91, 17))
        self.turn_right_center_lane.setObjectName("turn_right_center_lane")
        self.go_forwar_center_lane = QtWidgets.QCheckBox(self.center_lane)
        self.go_forwar_center_lane.setGeometry(QtCore.QRect(140, 20, 91, 17))
        self.go_forwar_center_lane.setObjectName("go_forwar_center_lane")
        self.turn_left_center_lane = QtWidgets.QCheckBox(self.center_lane)
        self.turn_left_center_lane.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.turn_left_center_lane.setObjectName("turn_left_center_lane")
        self.red_light_center = QtWidgets.QCheckBox(self.center_lane)
        self.red_light_center.setGeometry(QtCore.QRect(380, 20, 71, 17))
        self.red_light_center.setObjectName("red_light_center")
        self.tabWidget.addTab(self.center_lane, "")
        self.right_lane = QtWidgets.QWidget()
        self.right_lane.setStyleSheet("QWidget {\n"
"background-color: #d9d9d9;\n"
"}")
        self.right_lane.setObjectName("right_lane")
        self.turn_right_right_lane = QtWidgets.QCheckBox(self.right_lane)
        self.turn_right_right_lane.setGeometry(QtCore.QRect(260, 20, 91, 17))
        self.turn_right_right_lane.setObjectName("turn_right_right_lane")
        self.go_forward_right_lane = QtWidgets.QCheckBox(self.right_lane)
        self.go_forward_right_lane.setGeometry(QtCore.QRect(140, 20, 91, 17))
        self.go_forward_right_lane.setObjectName("go_forward_right_lane")
        self.turn_left_right_lane = QtWidgets.QCheckBox(self.right_lane)
        self.turn_left_right_lane.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.turn_left_right_lane.setObjectName("turn_left_right_lane")
        self.red_light_right = QtWidgets.QCheckBox(self.right_lane)
        self.red_light_right.setGeometry(QtCore.QRect(380, 20, 71, 17))
        self.red_light_right.setObjectName("red_light_right")
        self.tabWidget.addTab(self.right_lane, "")
        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)
        self.stackedWidget.setCurrentIndex(5)
        self.exit_btn_2.clicked.connect(App.close) # type: ignore
        # self.home_btn_2.toggled['bool'].connect(self.home_btn_2.setChecked)
        self.dashborad_btn_2.toggled['bool'].connect(self.dashborad_btn_2.setChecked) # type: ignore
        self.listcam_btn_menu.toggled['bool'].connect(self.listcam_btn_menu.setChecked) # type: ignore
        self.videoviolation_btn_menu.toggled['bool'].connect(self.videoviolation_btn_menu.setChecked) # type: ignore
        self.statistic_btn_menu.toggled['bool'].connect(self.statistic_btn_menu.setChecked)

        

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        self.dashboard.hide()
        self.centralapp.show()
        # self.centralapp.hide()
        # self.Draw.hide()
        self.widget.hide()
        self.widget_addcam.hide()
        # self.widget_addcam.show()
        # self.widget_campage.hide()
        

        App.setWindowTitle(_translate("App", "App"))
        self.Hidepassword.hide()
        self.TitleLogin.setText(_translate("App", "LOGIN"))
        self.Email.setPlaceholderText(_translate("App", "Enter Email"))
        self.password.setPlaceholderText(_translate("App", "Enter password"))
        self.AppNametext.setText(_translate("App", "MOT CONTROL PANEL"))
        self.pushButton.setText(_translate("App", "LOGIN"))
        self.checkBox.setText(_translate("App", "Keep Login"))
        self.wellcomebacktext.setText(_translate("App", "Wellcome back!"))
        self.helloText.setText(_translate("App", "Xin Chào Bạn !"))
        self.nameInfor.setText(_translate("App", "Nguyễn Xuân Phúc"))
        self.dateofbirthInfor.setText(_translate("App", "01/01/2022"))
        self.logoutButton.setText(_translate("App", "Đăng Xuất"))
        self.listcamPage.setText(_translate("App", "Danh sách Camera"))
        self.videoviolationPage.setText(_translate("App", "Video vi phạm"))
        self.ChartPage.setText(_translate("App", "Thống kê"))
        self.createaccountPage.setText(_translate("App", "Tạo tại khoản"))
        self.logo_label_3.setText(_translate("App", "CONTROL PANEL"))
        # self.home_btn_2.setText(_translate("App", "Home"))
        self.dashborad_btn_2.setText(_translate("App", "Dashboard"))
        self.listcam_btn_menu.setText(_translate("App", "Danh sách camera"))
        self.videoviolation_btn_menu.setText(_translate("App", "Video vi phạm"))
        self.statistic_btn_menu.setText(_translate("App", "Thông kê"))
        self.exit_btn_2.setText(_translate("App", "Exit"))
        self.search_input.setPlaceholderText(_translate("App", "Search..."))
        # self.label_5.setText(_translate("App", "Danh sách camera"))
        # self.label_6.setText(_translate("App", "Danh sách camera 1"))
        # self.label_4.setText(_translate("App", "Danh sách camera 2"))
        # # self.label_7.setText(_translate("App", "Danh sách camera 13"))
        # self.label_8.setText(_translate("App", "Danh sách camera 113"))
        self.nameuser.setText(_translate("App", "Admin"))
        self.nametxt.setText(_translate("App", "Admin"))
        self.label_name.setText(_translate("App", "Tên"))
        self.label_date.setText(_translate("App", "Ngày Sinh"))
        self.datetxt.setText(_translate("App", "23/05/2002"))
        self.emailtxt.setText(_translate("App", "1@gmail.com"))
        self.label_email.setText(_translate("App", "Email"))
        self.label_nphone.setText(_translate("App", "Số điện thoại"))
        self.nphonetxt.setText(_translate("App", "1234"))
        self.logout_btn.setText(_translate("App", "Đăng xuất"))
        self.changeinfor_btn.setText(_translate("App", "Thay đổi thông tin"))

        self.label_locationcam.setText(_translate("App", "Địa chỉ"))
        self.label_district.setText(_translate("App", "Quận :"))
        self.label_wards.setText(_translate("App", "Phường :"))
        self.addcam_btn.setText(_translate("App", "Thêm camera"))
        self.preview_btn.setText(_translate("App", "Xem trước"))
        self.label_listcam.setText(_translate("App", "Danh sách camera"))
        self.label_linkcam.setText(_translate("App", "Link camera :"))
        self.label_namecam.setText(_translate("App", "Tên cam :"))
        # self.turn_left_center_lane.setText("Turn left")
        # self.turn_left_center_lane.setText(_translate("App","Turn left"))
        self.turn_left_left_lane.setText(_translate("App", "Turn left"))
        self.go_forward_left_lane.setText(_translate("App", "Go forward"))
        self.turn_right_left_lane.setText(_translate("App", "Turn right"))
        self.red_light_left.setText(_translate("App", "Red light"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.left_lane), _translate("App", "Left lane"))
        self.turn_right_center_lane.setText(_translate("App", "Turn right"))
        self.go_forwar_center_lane.setText(_translate("App", "Go forward"))
        self.turn_left_center_lane.setText(_translate("App", "Turn left"))
        self.red_light_center.setText(_translate("App", "Red light"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.center_lane), _translate("App", "Center lane"))
        self.turn_right_right_lane.setText(_translate("App", "Turn right"))
        self.go_forward_right_lane.setText(_translate("App", "Go forward"))
        self.turn_left_right_lane.setText(_translate("App", "Turn left"))
        self.red_light_right.setText(_translate("App", "Red light"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.right_lane), _translate("App", "Right lane"))
